    ["xkScania1"] = {"Scania 1 - S500",349000, "<img src='https://github.com/BRFX-Shop/Cars/blob/main/xkScania1.png?raw=true' width='300' height='300'/>"},
    ["xkScania2"] = {"Scania 2 - S540",410000, "<img src='https://github.com/BRFX-Shop/Cars/blob/main/xkScania2.png?raw=true' width='300' height='300'/>"},
    ["xkScania3"] = {"Scania 3 - S540 2",876000, "<img src='https://github.com/BRFX-Shop/Cars/blob/main/xkScania3.png?raw=true' width='300' height='300'/>"},
    ["xkScania4"] = {"Scania 4 - S540 3",218500, "<img src='https://github.com/BRFX-Shop/Cars/blob/main/xkScania4.png?raw=true' width='300' height='300'/>"},
    ["xkScania5"] = {"Scania 5 - S770",478000, "<img src='https://github.com/BRFX-Shop/Cars/blob/main/xkScania5.png?raw=true' width='360' height='240'/>"},
    ["xkScania6"] = {"Scania 6 - S590",864000, "<img src='https://github.com/BRFX-Shop/Cars/blob/main/xkScania6.png?raw=true' width='360' height='240'/>"},
    ["xkScania7"] = {"Scania 7 - S540 4",987000, "<img src='https://github.com/BRFX-Shop/Cars/blob/main/xkScania7.png?raw=true' width='360' height='240'/>"},
    ["xkVolvo1"] = {"Volvo 1 - 540",1050000, "<img src='https://github.com/BRFX-Shop/Cars/blob/main/xkVolvo1.png?raw=true' width='360' height='240'/>"},
    ["xkVolvo2"] = {"Volvo 2 - 540 2",889000, "<img src='https://github.com/BRFX-Shop/Cars/blob/main/xkVolvo2.png?raw=true' width='360' height='240'/>"},
    ["xkVolvo3"] = {"Volvo 3 - 780",2250000, "<img src='https://github.com/BRFX-Shop/Cars/blob/main/xkVolvo3.png?raw=true' width='360' height='240'/>"},
	
	--- Trailers / العربايات
	["xkScania1Trailer"] = {"Scania 1 - Yellow Trailer",41000, "<img src='https://github.com/BRFX-Shop/Cars/blob/main/xkScania1Trailer.png?raw=true' width='360' height='240'/>"},
    ["xkScania2Trailer"] = {"Scania 2 - Black&Gold Trailer",87000, "<img src='https://github.com/BRFX-Shop/Cars/blob/main/xkScania2Trailer.png?raw=true' width='360' height='240'/>"},
    ["xkScania3Trailer"] = {"Scania 3 - Blue Trailer",119000, "<img src='https://github.com/BRFX-Shop/Cars/blob/main/xkScania3Trailer.png?raw=true' width='360' height='240'/>"},
    ["xkScania4Trailer"] = {"Scania 4 - Black Trailer",46000, "<img src='https://github.com/BRFX-Shop/Cars/blob/main/xkScania4Trailer.png?raw=true' width='300' height='300'/>"},
    ["xkScania5Trailer"] = {"Scania 5 - Black&Red Trailer",57000, "<img src='https://github.com/BRFX-Shop/Cars/blob/main/xkScania5Trailer.png?raw=true' width='360' height='240'/>"},
    ["xkScania6Trailer"] = {"Scania 6 - Wheelloader Trailer",89000, "<img src='https://github.com/BRFX-Shop/Cars/blob/main/xkScania6Trailer.png?raw=true' width='360' height='240'/>"},
    ["xkScania7Trailer"] = {"Scania 7 - Black&Gray Trailer",121000, "<img src='https://github.com/BRFX-Shop/Cars/blob/main/xkScania7Trailer.png?raw=true' width='360' height='240'/>"},
    ["xkVolvo1Trailer"] = {"Volvo 1 - White Trailer",189000, "<img src='https://github.com/BRFX-Shop/Cars/blob/main/xkVolvo1Trailer.png?raw=true' width='360' height='240'/>"},
    ["xkVolvo2Trailer"] = {"Volvo 2 - Blue&Green Trailer",62000, "<img src='https://github.com/BRFX-Shop/Cars/blob/main/xkVolvo2Trailer.png?raw=true' width='360' height='240'/>"},
    ["xkVolvo3Trailer"] = {"Volvo 3 - Green Trailer",83000, "<img src='https://github.com/BRFX-Shop/Cars/blob/main/xkVolvo3Trailer.png?raw=true' width='360' height='240'/>"},